spring.application.name=maple
discord.bot.token=MTMzMTUzOTU1Mjc2NjEzMjI5NQ.GOmYoe.U7FOue9E-fVq5MqK7fBlIjTUq4bagUk-daOKFk

# H2 ?? ?? (?? ????? ??? ??)
spring.datasource.url=jdbc:h2:file:./data/maplebot;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ?? ? H2 ?? (?????? DB ?? ?? ??: http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console